### ISSUE TITLE
[BUG] Get-SqlPackagePath.ps1 does not find SqlPackage.exe if installed as part of a SQL Server installation

### ISSUE THREAD

**Issue by zejji** [DrJohnT/AzureDevOpsExtensionsForSqlServer#26]
For example, with a freshly installed installation of SQL Server 2017 on Windows Server 2019 using Chocolately, the correct location for SqlPackage.exe is:
```    
C:\Program Files\Microsoft SQL Server\150\DAC\bin\SqlPackage.exe
```

This path (or the equivalent path for any other version of SQL Server - see [here](https://superuser.com/questions/429423/where-can-i-obtain-the-sqlpackage-command-line-utility#656497)) is not searched as part of `Get-SqlPackagePath.ps1`.

The workaround appears to be to specify a 'CustomSqlPackageInstallLocation' environment variable, but the script would be more user-friendly if it searched all the default SQL Server install locations.

**Comment by DrJohnT** [comment]
@zejji  
I upgraded the way the code works so that it covers more locations.  I have now republished both the Azure DevOps extension where you changed the code and the source PowerShell gallery module (where your code changes should have gone!).

See
https://marketplace.visualstudio.com/items?itemName=DrJohnExtensions.PublishDacPac
https://www.powershellgallery.com/packages/PublishDacPac/

**Comment by zejji** [comment]
@DrJohnT - thank you, much appreciated!

**Comment by zejji** [comment]
Confirmed working correctly in our pipeline 👍
