### ISSUE TITLE
Run SQL / SQLCMD Scripts passing multiple SQLCMD variables

### ISSUE THREAD

**Issue by sumateeka** [DrJohnT/AzureDevOpsExtensionsForSqlServer#29]
Will this tool identify the previously ran scripts? Because I don't want to rerun the scripts each build/release want to run only newly added scripts. So is there a way it can track and not run the scripts ? May be by filename or something?

**Comment by DrJohnT** [comment]
In your pipeline you could have a PowerShell script that moves the SqlCmd scripts which have just been run into a "run" folder.

Otherwise, I suggest you use SQL Server Data Tools to generate the deployment / upgrade scripts on the fly.  Much easier.
Then you can use my PublishDacPac DevOps extension to do the DacPac deployments: https://marketplace.visualstudio.com/items?itemName=DrJohnExtensions.PublishDacPac
